# define filters for file changes
# to trigger unit tests

# filter for changes
# to workflow
workflow: &workflow
  - '.github/filters.yaml'
  - '.github/workflows/unit-tests.yaml'
  - '.github/workflows/pre-commit.yaml'

# libraries
libs/injection/:
  - *workflow
  - 'libs/injection/**'
  - 'libs/base/**'

libs/architectures/:
  - *workflow
  - 'libs/architectures/**'
  
libs/data/:
  - *workflow
  - 'libs/data/**'
  - 'ml4gw/**'
  - 'libs/base/**'

# projects
projects/sandbox/data_generation/:
  - *workflow
  - 'ml4gw/**'
  - 'projects/sandbox/data_generation/**'
  - 'libs/injection/**'
