[tool.poetry]
name = "hermes"
version = "0.0.1"
description = "Inference-as-a-Service deployment made simple"
authors = [
    "Alec Gunny <alec.gunny@ligo.org>",
]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.16"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | _build
  | dist
  | docs
)/
'''

[tool.isort]
known_first_party = ["hermes"]
multi_line_output = 3
include_trailing_comma = true

[build-system]
requires = ["poetry>=1.2"]
build-backend = "poetry.masonry.api"
