name: unit-tests
 
on:
  pull_request:
   types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      libraries: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter 
      with:
        filters: .github/filters.yaml
    if: github.event.pull_request.draft == false  
  tests:
    runs-on: ubuntu-latest
    needs: changes
    strategy:
      fail-fast: true # is this desired behavior here?
      matrix:
        library: ${{ fromJSON(needs.changes.outputs.libraries) }}
        include: 
          - library: 'libs/data/'
            args: '-m "not gpu"'
        exclude:
          # don't run non-existent .github/workflow tests
          - library: 'workflow'
    permissions:
      packages: read
    container:
      image: ghcr.io/ml4gw/pinto:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      volumes:
        - ${{ github.workspace }}:/github/workspace
    env:
        CONDA_DEFAULT_ENV: base
        CONDA_PREFIX: /opt/conda
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # install gcc for bilby build
      # TODO: not every library/project needs this
      -
        name: install gcc
        run: apt update && apt install -y build-essential

      # build the project's environment
      -
        name: build environment
        env:
          test_dir: /github/workspace/${{ matrix.library }}
          
        # TODO: use case statement here, or add separate matrix.build_args
        run: |
            if [[ "${{ matrix.library }}" == "libs/architectures/" ]]; then
                FLAGS="-E wrapper"
            else
                FLAGS=""
            fi
            pinto -p $test_dir build $FLAGS
            printenv
        shell: bash
      
      # run tests
      - name: run tests 
        env:
          test_dir: /github/workspace/${{ matrix.library }}
        run: pinto -p $test_dir run pytest $test_dir/tests ${{matrix.args}}
        shell: bash
        
